name:         text-gl
version:      "0.1"
category:     Graphics
synopsis:     Text editing on top of freetype-gl-mini
description:  Text editing on top of freetype-gl-mini
license:      BSD3
author:       Luke Iannini
copyright:    Luke Iannini
maintainer:   lukexi@me.com
github:       lukexi/text-gl

ghc-prof-options:    -Wall -O2 -fprof-auto
ghc-options:         -Wall -O2

dependencies:
  - base
  - stm
  - gl
  - linear
  - gl-pal
  - vr-pal
  - sdl2
  - containers
  - mtl
  - random
  - lens-extra
  - halive
  - linear-extra
  - freetype-gl-mini
  - text

library:
  source-dirs:
    - src

tests:
  basic:
    ghc-options: -threaded -rtsopts
    source-dirs:
      - test
    main: TestBasic.hs
    other-modules: []
    dependencies: text-gl
  scaling:
    ghc-options: -threaded -rtsopts
    source-dirs:
      - test
    main: TestScaling.hs
    other-modules: []
    dependencies: text-gl
  buffer:
    ghc-options: -threaded -rtsopts
    source-dirs:
      - test
    main: TestBuffer.hs
    other-modules: []
    dependencies: text-gl
  buffer-scroll:
    ghc-options: -threaded -rtsopts
    source-dirs:
      - test
    main: TestBufferScroll.hs
    other-modules: []
    dependencies: text-gl
